.TH river-shifttags 1 2021-10-24 "General Commands Manual"
.
.SH NAME
.P
river-shifttags \- a shifttags utility for the river Wayland compositor.
.
.
.SH SYNOPSIS
.SY river-shifttags
.OP \-\-shifts value
.OP \-\-num-tags value
.OP \-\-start value
.YS
.
.SY river-shifttags
.OP \-\-help
.YS
.
.
.SH DESCRIPTION
.P
A utility for the river Wayland compositor that will rotate the currently
focused tags.
.
.
.SH OPTIONS
.P
\fB--help\fR
.RS
Print help text and exit.
.RE
.
.P
\fB--shifts\fR \fIvalue\fR
.RS

Number of shifts. A positive integer \fIn\fR will rotate the river tags \fIn\fR
times to the right. A negative integer will rotate river tags to the
left.

(Default is 1).
.RE
.
.P
\fB--num-tags\fR \fIvalue\fR
.RS
Amount of used tags.
This configured how many of river's 32 tags you are interested in, starting at
the beginning. river-shifttags will not rotate the tags outside this range.
\fIvalue\fR must be an integer between 1 and 32.

(Default is 9).
.RE
.
.P
\fB--start\fR \fIsize\fR
.RS
This configures the first tag in the output to rotate from.
\fIsize\fR must be an integer between 0 and 31.

(Default is 0).
.SH EXAMPLE
.P
For mapping Super + '[' and ']' keys to cycle to left and right tags:
.P
.RS
.EX
riverctl map normal Mod4 BRACKETRIGHT spawn  'river-shifttags'
riverctl map normal Mod4 BRACKETLEFT spawn  'river-shifttags --shifts -1'
.EE
.RE
.
.
.SH SEE ALSO
.BR river (1)
